#!/bin/bash
_i2chelper(){
    MODULES="i2c-dev i2c-bcm2708"
    MODULE_FILE="/etc/modules-load.d/raspberrypi.conf"

    if [[ -a $MODULE_FILE ]]; then
        for MODULE in $MODULES
        do
            echo -n "Comprobar el modulo ${MODULE}  "
            if grep -q $MODULE "${MODULE_FILE}"; then
                echo "ENCONTRADO"
            else
                echo "${MODULE}" >> $MODULE_FILE 2>/dev/null && echo "AÑADIDO" || { echo "ERROR:  No se puede escribir el archivo ${MODULE_FILE}"; exit 1; }
            fi
        done
    else
        echo "INFO:  ${MODULE_FILE} No encontrado"
        for MODULE in $MODULES
        do
            echo "${MODULE}" >> $MODULE_FILE 2>/dev/null || { echo "ERROR:  No se puede escribir el archivo ${MODULE_FILE}"; exit 1; }
        done
        echo "INFO:  ${MODULE_FILE} Craación correcta"
    fi
}
_install_overlay(){
    FILE=/boot/config.txt 
    [ -w "$FILE" ] || { echo "ERROR No se puede escribir en ${FILE} imposible continuar"; exit 1; }
    SYSMODEL=$( awk '{ print $0 }' /proc/device-tree/model | sed 's|Raspberry Pi||;s|Rev.*||;s|Model||;s|Zero|0|;s|Plus|+|;s|B| |;s|A| |;s| ||g' )

    echo -n "Buscar config.txt para overlay ... "
    grep -i '^dtoverlay=argonone' $FILE 1> /dev/null && { echo "ENCONTRADO"; exit 0; } || echo "NO ENCONTRADO"
    cp $FILE $FILE.backup
    echo -n "Insertar overlay en ${FILE} ... "
    if [[ `grep -i "^\[pi${SYSMODEL}\]" $FILE` ]]
    then
        sed  -i "/^\[pi${SYSMODEL}\]/a dtoverlay=argonone" $FILE && echo "CORRECTO";
    else
        echo "dtoverlay=argonone" >> $FILE && echo "CORRECTO";
    fi
    unset FILE
}
_start_service(){
    echo -n "Activando servicio "
    systemctl enable argononed &>/dev/null && echo "Con exito" || echo "Fallido"
    echo -n "Arrancando servicio "
    systemctl start &>/dev/null && echo "Con exito" || ( [ $? -eq 124 ] && echo "Tiempo excedido" || echo "Fallido" )
}
# arg 1:  the new package version
post_install() {
    _i2chelper
    _install_overlay
    _start_service
}

# arg 1:  the old package version
pre_remove() {
    echo -n "Parando servicio "
    systemctl stop &>/dev/null && echo "Con exito" || ( [ $? -eq 124 ] && echo "Tiempo excedido" || echo "Fallido" )
    echo -n "Desactivando servicio "
    systemctl disable argononed &>/dev/null && echo "Con exito" || echo "Fallido"
}

# arg 1:  the old package version
post_remove() {
    echo "Borrar dtoverlay=argonone de $(BOOTLOC)/config.txt"
    cp /boot/config.txt /boot/config.argononed.backup
    sed -i '/dtoverlay=argonone/d' /boot/config.txt
    echo "Desintalación completa"
}
